export const about = {
  readmeLabel: 'README.md',
  fileLabel: 'skills.ts',
  readmeBlocks: [
    "I'm a software engineer with a B.S. in Computer Science from St. John's University. I'm most interested in backend systems, machine learning, and the kind of technical work that turns rough ideas into software people can actually use.",
    'A lot of my recent work has been in full-stack products and data-heavy systems, with a growing focus on AI and machine learning. I enjoy building APIs, shaping platform architecture, and working on ML-driven systems that connect strong technical ideas to something useful in practice.',
    "I'm especially drawn to projects that need both good engineering judgment and attention to detail. Whether the work is product-focused or more research-oriented, I like building things that feel practical, thoughtful, and technically strong.",
  ],
  defaultMode: 'programming',
  commandModes: [
    {
      id: 'programming',
      label: 'programming',
      description: 'Languages, frameworks, and application-layer tooling.',
      skills: [
        'Python',
        'Golang',
        'C#/.NET',
        'C++',
        'Java',
        'SQL',
        'TypeScript/JavaScript',
        'FastAPI',
        'Next.js',
        'React',
      ],
    },
    {
      id: 'ai_ml',
      label: 'ai_ml',
      description: 'Modeling, retrieval, and ML tooling I work with most.',
      skills: [
        'PyTorch',
        'TensorFlow',
        'Hugging Face Transformers',
        'RAG',
        'NLP',
        'vector search',
        'Pandas',
        'NumPy',
        'scikit-learn',
      ],
    },
    {
      id: 'data_infra',
      label: 'data_infra',
      description: 'Infra, orchestration, streaming, and storage systems.',
      skills: [
        'AWS',
        'Kubernetes',
        'Terraform',
        'Apache Kafka',
        'PostgreSQL',
        'Redis',
        'Docker',
        'CI/CD',
      ],
    },
  ],
};
