export const about = {
  fileLabel: 'skills.ts',
  lead: "Software engineer with a B.S. in Computer Science from St. John's University.",
  support:
    'I build backend systems, APIs, machine learning workflows, and full-stack software with a focus on reliability, data flow, and real-world use. My strongest interests sit around distributed systems, data-heavy applications, and applied AI.',
  defaultMode: 'programming',
  commandModes: [
    {
      id: 'programming',
      label: 'programming',
      description: 'Languages, frameworks, and application-layer tooling.',
      skills: [
        'Python',
        'Golang',
        'C#/.NET',
        'C++',
        'Java',
        'SQL',
        'TypeScript/JavaScript',
        'FastAPI',
        'Next.js',
        'React',
      ],
    },
    {
      id: 'ai_ml',
      label: 'ai_ml',
      description: 'Modeling, retrieval, and ML tooling I work with most.',
      skills: [
        'PyTorch',
        'TensorFlow',
        'Hugging Face Transformers',
        'RAG',
        'NLP',
        'vector search',
        'Pandas',
        'NumPy',
        'scikit-learn',
      ],
    },
    {
      id: 'data_infra',
      label: 'data_infra',
      description: 'Infra, orchestration, streaming, and storage systems.',
      skills: [
        'AWS',
        'Kubernetes',
        'Terraform',
        'Apache Kafka',
        'PostgreSQL',
        'Redis',
        'Docker',
        'CI/CD',
      ],
    },
  ],
};
