export const featuredProjects = [
  {
    title: 'Featured Project Slot 01',
    summary:
      'Reserved for the strongest end-to-end build on the site, where product thinking and engineering depth both deserve a full case-study treatment.',
    detail:
      'Use this slot for the project that best shows architecture, shipped scope, and user value working together instead of relying on visuals alone.',
    tags: ['Full-stack', 'Primary Case Study', 'Repo Pending'],
    githubUrl: '',
    liveUrl: '',
    repoLabel: 'flagship-product',
    branch: 'main',
    buildState: 'build-ready',
    projectType: 'Product case study',
    role: 'Lead engineer',
    primaryStack: 'Next.js, Node.js, PostgreSQL',
    status: 'Queued for showcase',
    previewFiles: ['README.md', 'stack.ts', 'release-notes.md'],
    snapshot: ['user flows mapped', 'service boundaries outlined', 'delivery story ready'],
  },
  {
    title: 'Featured Project Slot 02',
    summary:
      'Reserved for a backend, data, or systems-focused build that adds technical range and gives the portfolio a stronger engineering backbone.',
    detail:
      'Use this slot for work where infrastructure, APIs, performance, or data orchestration are the core story and the repo itself can carry the explanation.',
    tags: ['Backend', 'Systems', 'Repo Pending'],
    githubUrl: '',
    liveUrl: '',
    repoLabel: 'systems-build',
    branch: 'staging',
    buildState: 'in-review',
    projectType: 'Systems snapshot',
    role: 'Builder / architect',
    primaryStack: 'APIs, data pipelines, infra',
    status: 'Awaiting final repo',
    previewFiles: ['README.md', 'pipeline.yaml', 'ops-checklist.txt'],
    snapshot: ['interfaces drafted', 'infra notes collected', 'performance story pending'],
  },
];

export const projectArchive = [
  {
    title: 'Project Slot 03',
    summary: 'Use for a smaller but credible build that still adds a clean technical signal to the archive.',
    tags: ['Project Type', 'Tech Tags'],
    githubUrl: '',
    liveUrl: '',
    repoLabel: 'tooling-experiment',
    buildState: 'build-ready',
    projectType: 'Utility / experiment',
    role: 'Solo build',
    primaryStack: 'Replace with stack',
    status: 'Archive candidate',
  },
  {
    title: 'Project Slot 04',
    summary: 'Use for an academic, research, or exploratory project with a clear technical angle.',
    tags: ['Project Type', 'Tech Tags'],
    githubUrl: '',
    liveUrl: '',
    repoLabel: 'research-prototype',
    buildState: 'notes-open',
    projectType: 'Research build',
    role: 'Team contributor',
    primaryStack: 'Replace with stack',
    status: 'Casefile open',
  },
  {
    title: 'Project Slot 05',
    summary: 'Use for a project that shows range without competing with the featured case studies.',
    tags: ['Project Type', 'Tech Tags'],
    githubUrl: '',
    liveUrl: '',
    repoLabel: 'applied-build',
    buildState: 'deployed',
    projectType: 'Applied product',
    role: 'Engineer',
    primaryStack: 'Replace with stack',
    status: 'Ready to profile',
  },
  {
    title: 'Project Slot 06',
    summary: 'Use for a practical build with clean execution and a clear reason to keep in the archive.',
    tags: ['Project Type', 'Tech Tags'],
    githubUrl: '',
    liveUrl: '',
    repoLabel: 'supporting-project',
    buildState: 'in-progress',
    projectType: 'Supporting build',
    role: 'Engineer',
    primaryStack: 'Replace with stack',
    status: 'Needs final write-up',
  },
];
